<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Forget_Password.png" />
    <None Remove="Images\LG..jpg" />
    <None Remove="PLANANET.png" />
    <None Remove="Vector Oeil Icône PNG , Les Yeux Clipart, Icônes Des Yeux, Icône Oeil PNG et vecteur pour téléchargement gratuit.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.4.25258.110" />
    <PackageReference Include="MVVMEssentials.WPF" Version="1.0.3" />
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Other\Adminn\Adminn.csproj" />
    <ProjectReference Include="..\Other\Employee\Employee.csproj" />
    <ProjectReference Include="..\Other\Supplier\Supplier.csproj" />
  </ItemGroup>

  <!--<ItemGroup>
    <None Remove="download-removebg-preview %281%29.png" />
    <None Remove="download__1_-removebg-preview.png" />
    <None Remove="dsd.png" />
    <None Remove="Facebook.png" />
    <None Remove="Images\Best_Cybersecurity_solutions_in_Wisconsin___X-Centric_IT_solutions__1_-removebg-preview.png" />
    <None Remove="Images\download-removebg-preview %281%29.png" />
    <None Remove="Images\download-removebg-preview.png" />
    <None Remove="Images\download__1_-removebg-preview.png" />
    <None Remove="Images\dsd.png" />
    <None Remove="Images\Facebook.png" />
    <None Remove="Images\FDGVDF.png" />
    <None Remove="Images\Instagram.png" />
    <None Remove="Images\KKK.jpg" />
    <None Remove="Images\La_transparence_mutuelle___clé_d_une_relation_client_durable-removebg-preview.png" />
    <None Remove="Images\logo_dolphin-removebg-preview.png" />
    <None Remove="Images\Watercolor and earth map vector - WeLoveSoLo.jpg" />
    <None Remove="Images\X.png" />
    <None Remove="Instagram.png" />
    <None Remove="Watercolor and earth map vector - WeLoveSoLo.jpg" />
    <None Remove="X.png" />
  </ItemGroup>-->

 

  <ItemGroup>
    <Resource Include="Images\Best_Cybersecurity_solutions_in_Wisconsin___X-Centric_IT_solutions__1_-removebg-preview.png" />
    <Resource Include="Images\download-removebg-preview (1).png" />
    <Resource Include="Images\download-removebg-preview.png" />
    <Resource Include="Images\download__1_-removebg-preview.png" />
    <Resource Include="Images\dsd.png" />
    <Resource Include="Images\Facebook.png" />
    <Resource Include="Images\FDGVDF.png" />
    <Resource Include="Images\Forget_Password.png" />
    <Resource Include="Images\Instagram.png" />
    <Resource Include="Images\KKK.jpg" />
    <Resource Include="Images\La_transparence_mutuelle___clé_d_une_relation_client_durable-removebg-preview.png" />
    <Resource Include="Images\LG..jpg" />
    <Resource Include="Images\logo_dolphin-removebg-preview.png" />
    <Resource Include="Images\Watercolor and earth map vector - WeLoveSoLo.jpg" />
    <Resource Include="Images\X.png" />
    <Resource Include="PLANANET.png" />
    <Resource Include="Vector Oeil Icône PNG , Les Yeux Clipart, Icônes Des Yeux, Icône Oeil PNG et vecteur pour téléchargement gratuit.jpg" />
  </ItemGroup>

 

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
  </ItemGroup>

	
</Project>
