<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\LG..jpg" />
  </ItemGroup>

 

  <ItemGroup>
    <Resource Include="Images\download-removebg-preview (1).png" />
    <Resource Include="Images\dsd.png" />
    <Resource Include="Images\Leonardo_Phoenix_10_Design_a_professional_and_visually_appeali_3.jpg" />
    <Content Include="Images\LG..jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

 

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks" Version="5.1.0" />
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

</Project>
